// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euayjiyowktjcxbjrugn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YXlqaXlvd2t0amN4YmpydWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODMxODYsImV4cCI6MjA2OTY1OTE4Nn0.fYS2b2_jhcPciobLgI1jataBUTpR9exDDgykEEysvno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});